<!DOCTYPE HTML>
<html>
	<head>
		<title>Web Me</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body>

		<!-- Wrapper -->
			<div id="wrapper" class="divided">

				<!-- One -->
					<section class="banner style1 orient-left content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-right">
						<div class="content">
							<h1>Aqilla Fadia Rahmani</h1>
							<p class="major">Saya biasa dipanggil Aqilla, saya lahir di Bekasi 24 Juni 2001. Sekarang,saya berumur16 tahun. Saya adalah anak ke -1 dari 3 bersaudara . Saya memiliki 2 adik perempuan . Saya tinggal di Bekasi tetapi saya sekarang saya tinggal di Bogor. Sekarang saya sekolah di SMK - SMAK Bogor yang biasa dikenal dengan SMA Kimia Bogor ( SMAKBO ). Awalnya saya tidak tahu tentang sekolah ini, tetapi orang tua dan saudara - saudara saya menceritakan tentang SMAKBo  dan bagaimana keadaaan saat dan sesudah sekolah di SMAKBo yang membuat saya tertarik untuk masuk sekolah ini. seperti yang orang lain bilang kalau sudah lulus dari SMAKBo akan mudah mendapat pekerjaan. Saya masuk SMAKBo melalui jalur test dan saat pengumuman tiba...Alhamdulillah saya lulus test...yaa yang artinya saya masuk sekolah ini.</p>
							<ul class="actions vertical">
								<li><a href="#first" class="button big wide smooth-scroll-middle">About My Hobby</a></li>
							</ul>
						</div>
						<div class="image">
							<img src="images/Profile.jpg" alt="" />
						</div>
					</section>

				<!-- Two -->
					<section class="banner style1 orient-right content-align-left image-position-center fullscreen onload-image-fade-in" id="first">
						<div class="content">
							<h2>Music</h2>
							<p>Salah satu hobi saya adalah mendengarkan musik, karena dalam kondisi mood apapun, dengan mendengarkan music, hari selalu enjoy dan senang walau galau sekalipun.</p>
							<ul class="actions vertical">
								<li><a href="#second" class="button big wide smooth-scroll-middle">Next Hobby</a></li>
							</ul>
						</div>
						<div class="image">
							<img src="images/Music.jpg" alt="" />
						</div>
					</section>

				<!-- Three -->
					<section class="banner style1 orient-left content-align-left image-position-center fullscreen onload-image-fade-in" id="second">
						<div class="content">
							<h2>Relax At Cafe</h2>
							<p>Kata orang - orang sih cafe itu buat anak orang kaya. Tapi gua ke cafe cuma buat nyari Wi-Fi gratis :D.</p>
							<ul class="actions vertical">
								<li><a href="#third" class="button big wide smooth-scroll-middle">My Account</a></li>
							</ul>
						</div>
						<div class="image">
							<img src="images/Cafe.jpg" alt="" />
						</div>
					</section>

				<!-- Four -->
					<section class="wrapper style1 align-center" id="third">
						<div class="inner medium">
							<h2>Get in touch</h2>
							<form method="post" action="#">
								<div class="field half first">
									<label for="name">Name</label>
									<input type="text" name="name" id="name" value="" />
								</div>
								<div class="field half">
									<label for="email">Email</label>
									<input type="email" name="email" id="email" value="" />
								</div>
								<div class="field">
									<label for="message">Message</label>
									<textarea name="message" id="message" rows="6"></textarea>
								</div>
								<ul class="actions">
									<li><input type="submit" name="submit" id="submit" value="Send Message" /></li>
								</ul>
							</form>

						</div>
					</section>

				<!-- Footer -->
					<footer class="wrapper style1 align-center">
						<div class="inner">
							<ul class="icons">
								<li><a href="https://www.instagram.com/aqilla.fdr/?hl=en" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
								<li><a href="https://plus.google.com/u/0/113523214353715510880" class="icon style2 fa-envelope"><span class="label">Email</span></a></li>
							</ul>
							<p>&copy; Untitled. Design: <a href="#">SKY 2018</a>.</p>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>
